name: Deploy Frontend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  TF_VERSION: 1.6.0
  NODE_VERSION: 18

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run type check
        run: npm run type-check
      
      - name: Run linter
        run: npm run lint
      
      - name: Build application
        run: npm run build

  terraform-plan:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION || 'us-west-2' }}
      
      - name: Terraform Init
        working-directory: terraform
        run: terraform init
      
      - name: Terraform Plan
        working-directory: terraform
        run: |
          terraform plan \
            -var="aws_region=${{ vars.AWS_REGION || 'us-west-2' }}" \
            -var="environment=${{ vars.ENVIRONMENT || 'dev' }}" \
            -var="domain_name=${{ vars.DOMAIN_NAME || '' }}" \
            -var="certificate_arn=${{ vars.CERTIFICATE_ARN || '' }}" \
            -var="project_name=legacy-health-frontend"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build application
        run: npm run build
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION || 'us-west-2' }}
      
      - name: Terraform Init
        working-directory: terraform
        run: terraform init
      
      - name: Terraform Apply
        working-directory: terraform
        run: |
          terraform apply -auto-approve \
            -var="aws_region=${{ vars.AWS_REGION || 'us-west-2' }}" \
            -var="environment=${{ vars.ENVIRONMENT || 'dev' }}" \
            -var="domain_name=${{ vars.DOMAIN_NAME || '' }}" \
            -var="certificate_arn=${{ vars.CERTIFICATE_ARN || '' }}" \
            -var="project_name=legacy-health-frontend"
      
      - name: Get S3 bucket name
        id: bucket
        working-directory: terraform
        run: echo "name=$(terraform output -raw s3_bucket_name)" >> $GITHUB_OUTPUT
      
      - name: Deploy to S3
        run: aws s3 sync dist/ s3://${{ steps.bucket.outputs.name }} --delete
      
      - name: Get CloudFront distribution ID
        id: cloudfront
        working-directory: terraform
        run: echo "id=$(terraform output -raw cloudfront_distribution_id)" >> $GITHUB_OUTPUT
      
      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ steps.cloudfront.outputs.id }} --paths "/*"